---
kind: Service
apiVersion: v1
metadata:
  name: gceme-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: gowebapp

  
---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gowebapp
spec:
  replicas:
  template:
    metadata:
      name: gowebapp
      labels:
        app: gowebapp
        env: dev
    spec:
      containers:
      - name: gowebapp
        image: gcr.io/cloud-solutions-images/gceme:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        ports:
          containerPort: 80
