kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gowebapp-canary
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: gowebapp
        role: frontend
        env: canary
    spec:
      containers:
      - name: frontend
        image: imageversion
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: ["sh", "-c", "app -frontend=true -port=80"]
        ports:
        - name: frontend
          containerPort: 80
