kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gowebapp-production
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: gowebapp
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: gcr.io/cloud-solutions-images/gceme:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: ["sh", "-c", "app -frontend=true -port=80"]
        ports:
        - name: frontend
          containerPort: 80
